### PR TITLE
Eslint and Prettier into the package.json file

### LINKED ISSUE #3: need code refactoring
right now every `.js` files is just a mess, anyone up for refactoring them?

### PR DESCRIPTION
**Pull request by osmarpetry**
`.prettierrc` file is in this PR: https://github.com/neizod/open-sky/pull/4

@neizod you should check the eslint rules that I disabled, because I don't know how it can affect in your code

Fixes #3

### CODE REVIEW

**Comment by neizod** [comment]
@osmarpetry I just merge #4 and now some files are conflicted, could you lint that again? Thanks!

**Comment by evandroabukamel** [comment]
@osmarpetry , could you solve the conflict, please?

**Comment by osmarpetry** [comment]
@neizod conflicts are solved

**Comment by neizod** [comment]
Thank you @evandroabukamel and @osmarpetry for help improving this project. All PR merged.

**Pull request merged**
